#!/usr/bin/python3
"""Defines a class base"""

class Base:
    """Represent a base
       
       Attributes:
           --nb_objects (int): The number of instantiated Bases.
    """

    __nb_objects = 0

    def __init__(self, id=None):
        """Intialize a new Base

        Args:
            Id: Identity of the base
        """

    if id != None :
        return self.id = id
   else:
       Base . __nb_object += 1
       self.id = Base. __nb_objects
       

